Starting to migrate usable code out of jq_zshrc into jq_cleaned_zshrc

diff --git a/jq_zshrc b/jq_zshrc
--- a/jq_zshrc
+++ b/jq_zshrc
@@ -34,6 +34,9 @@ if ! zplug check --verbose; then
     fi
 fi
 
+# ZPLUG_CLONE_DEPTH=0
+zstyle ':zplug:tag' depth 0
+zplug load --verbose
 # nq Package Manager
 # oq linux
 # https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/command-not-found
@@ -431,23 +434,24 @@ source $HOME/60o_Doc_Qiuy/50_Environment/nq_version_control/oq_git/oq_shell/oq_z
 zplug "mollifier/anyframe"
 
 ########################################
-bindkey '^xb' anyframe-widget-cdr
-bindkey '^x^b' anyframe-widget-checkout-git-branch
-
-bindkey '^xr' anyframe-widget-execute-history
-bindkey '^x^r' anyframe-widget-execute-history
-
-bindkey '^xi' anyframe-widget-put-history
-bindkey '^x^i' anyframe-widget-put-history
-
-bindkey '^xg' anyframe-widget-cd-ghq-repository
-bindkey '^x^g' anyframe-widget-cd-ghq-repository
-
-bindkey '^xk' anyframe-widget-kill
-bindkey '^x^k' anyframe-widget-kill
-
-bindkey '^xe' anyframe-widget-insert-git-branch
-bindkey '^x^e' anyframe-widget-insert-git-branch
+# UNSetting, need to tighten
+# bindkey '^xb' anyframe-widget-cdr
+# bindkey '^x^b' anyframe-widget-checkout-git-branch
+#
+# bindkey '^xr' anyframe-widget-execute-history
+# bindkey '^x^r' anyframe-widget-execute-history
+#
+# bindkey '^xi' anyframe-widget-put-history
+# bindkey '^x^i' anyframe-widget-put-history
+#
+# bindkey '^xg' anyframe-widget-cd-ghq-repository
+# bindkey '^x^g' anyframe-widget-cd-ghq-repository
+#
+# bindkey '^xk' anyframe-widget-kill
+# bindkey '^x^k' anyframe-widget-kill
+#
+# bindkey '^xe' anyframe-widget-insert-git-branch
+# bindkey '^x^e' anyframe-widget-insert-git-branch
 
 ########################################
 
@@ -1003,7 +1007,7 @@ function fzf_tmux_helper() {
   local cmd=$1
   shift
   tmux split-window -p 40 \
-    "bash -c \"\$(tmux send-keys -t $TMUX_PANE \"\$(source $HOME/.fzf.zsh; $cmd)\" $*)\""
+    "zsh -c \"\$(tmux send-keys -t $TMUX_PANE \"\$(source $HOME/.fzf.zsh; $cmd)\" $*)\""
 }
 
 # This is the function we are going to run in the split pane.
@@ -1017,8 +1021,46 @@ function fzf_tmux_dir() {
      sed "s/ /\\\\ /g" |
      paste -sd" " -' Space
 }
+# If you prefer to run fzf in full screen mode,
+# add --no-height to your $FZF_DEFAULT_OPTS like follows:
+# export FZF_DEFAULT_OPTS='--no-height --no-reverse'
+
+# Or if you prefer to start in a tmux split pane, set $FZF_TMUX to 1.
+export FZF_TMUX=1
+
+export FZF_CTRL_T_OPTS="--preview '(highlight -O ansi -l {} 2> /dev/null || cat {} || tree -C {}) 2> /dev/null | head -200'"
+
+export FZF_CTRL_R_OPTS="--preview 'echo {}' --preview-window down:3:hidden --bind '?:toggle-preview'"
 
 source $HOME/60o_Control_Qiuy/10_Activity/xq_concatenating/oq_shell/oq_zsh/xq_compile_mappings_vim.zsh
+#
+#
+
+
+# Will return non-zero status if the current directory is not managed by git
+function is_in_git_repo() {
+  git rev-parse HEAD > /dev/null 2>&1
+}
+
+function gt() {
+  # "Nothing to see here, move along"
+  is_in_git_repo || return
+
+  # Pass the list of the tags to fzf-tmux
+  # - "{}" in preview option is the placeholder for the highlighted entry
+  # - Preview window can display ANSI colors, so we enable --color=always
+  # - We can terminate `git show` once we have $LINES lines
+  git tag --sort -version:refname |
+    fzf-tmux --multi --preview-window right:70% \
+             --preview 'git show --color=always {} | head -'$LINES
+}
+
+# Then we bind it to a key.
+
+# To clean
+# bindkey -M '"\er": redraw-current-line'
+# bindkey -M '"\C-g\C-t": "$(gt)\e\C-e\er"'
+
 # oq Vim
 # function vqr() {
 #     local pathway
@@ -1041,7 +1083,7 @@ source $HOME/60o_Control_Qiuy/10_Activity/xq_concatenating/oq_shell/oq_zsh/xq_co
 
 
 # Scripts for searching Vim Qiuy configs
-source $HOME/1q_ctrl-qiuy/50_Environment/uq_searching/oq_zsh/oqo_search_configs_vim_qiuy.zsh
+source $HOME/1q_ctrl-qiuy/50_Environment/uq_searching/oq_zsh/oqo_scripts/oqo_search_configs_vim_qiuy.zsh
 # if [ -f '$HOME/40_Movement/40u_Searching/60o_Shell_Qiuy/60o_ZSH/60o_Plugins/50i_Production/sq40u-search-configs-vim-qiuy.sh' ]; then
 #     . "$HOME/40_Movement/40u_Searching/60o_Shell_Qiuy/60o_ZSH/60o_Plugins/50i_Production/sq40u-search-configs-vim-qiuy.sh"
 # fi
@@ -1058,3 +1100,5 @@ source $HOME/60o_Flow_Qiuy/50_Environment/nq_softlinks/10_Activity/rq_analysis/o
 zplug "zsh-users/zsh-syntax-highlighting"
 # zplug "zsh-users/zsh-syntax-highlighting", \
     # nice:10
+
+[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
